apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-v1
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8"><title>v1</title></head>
    <body><h1>Version 1 — STABLE</h1></body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-v2
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8"><title>v2</title></head>
    <body><h1>Version 2 — CANARY</h1></body>
    </html>